//------------------------------------------------------------------------------ 
// <auto-generated> 
//     This code was generated by a tool. 
// 
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.  
// </auto-generated> 
//------------------------------------------------------------------------------ 

namespace FinalProj
{


	public partial class Enquiry
	{

		/// <summary> 
		/// panelSuccess control. 
		/// </summary> 
		/// <remarks> 
		/// Auto-generated field. 
		/// To modify move field declaration from designer file to code-behind file. 
		/// </remarks> 
		protected global::System.Web.UI.WebControls.Panel panelSuccess;

		/// <summary> 
		/// lb_success control. 
		/// </summary> 
		/// <remarks> 
		/// Auto-generated field. 
		/// To modify move field declaration from designer file to code-behind file. 
		/// </remarks> 
		protected global::System.Web.UI.WebControls.Label lb_success;

		/// <summary> 
		/// panelError control. 
		/// </summary> 
		/// <remarks> 
		/// Auto-generated field. 
		/// To modify move field declaration from designer file to code-behind file. 
		/// </remarks> 
		protected global::System.Web.UI.WebControls.Panel panelError;

		/// <summary> 
		/// lb_error control. 
		/// </summary> 
		/// <remarks> 
		/// Auto-generated field. 
		/// To modify move field declaration from designer file to code-behind file. 
		/// </remarks> 
		protected global::System.Web.UI.WebControls.Label lb_error;

		/// <summary> 
		/// leaveEvent control. 
		/// </summary> 
		/// <remarks> 
		/// Auto-generated field. 
		/// To modify move field declaration from designer file to code-behind file. 
		/// </remarks> 
		protected global::System.Web.UI.WebControls.Button leaveEvent;

		/// <summary> 
		/// joinEvent control. 
		/// </summary> 
		/// <remarks> 
		/// Auto-generated field. 
		/// To modify move field declaration from designer file to code-behind file. 
		/// </remarks> 
		protected global::System.Web.UI.WebControls.Button joinEvent;

		/// <summary> 
		/// bookmarkEvent control. 
		/// </summary> 
		/// <remarks> 
		/// Auto-generated field. 
		/// To modify move field declaration from designer file to code-behind file. 
		/// </remarks> 
		protected global::System.Web.UI.WebControls.Button bookmarkEvent;

		/// <summary> 
		/// bookmarked control. 
		/// </summary> 
		/// <remarks> 
		/// Auto-generated field. 
		/// To modify move field declaration from designer file to code-behind file. 
		/// </remarks> 
		protected global::System.Web.UI.WebControls.Button bookmarked;

		/// <summary> 
		/// discussion control. 
		/// </summary> 
		/// <remarks> 
		/// Auto-generated field. 
		/// To modify move field declaration from designer file to code-behind file. 
		/// </remarks> 
		protected global::System.Web.UI.WebControls.Button discussion;

		/// <summary> 
		/// editEvent control. 
		/// </summary> 
		/// <remarks> 
		/// Auto-generated field. 
		/// To modify move field declaration from designer file to code-behind file. 
		/// </remarks> 
		protected global::System.Web.UI.WebControls.Button editEvent;

		/// <summary> 
		/// deleteEvent control. 
		/// </summary> 
		/// <remarks> 
		/// Auto-generated field. 
		/// To modify move field declaration from designer file to code-behind file. 
		/// </remarks> 
		protected global::System.Web.UI.WebControls.Button deleteEvent;

		/// <summary> 
		/// attendance control. 
		/// </summary> 
		/// <remarks> 
		/// Auto-generated field. 
		/// To modify move field declaration from designer file to code-behind file. 
		/// </remarks> 
		protected global::System.Web.UI.WebControls.Button attendance;

		/// <summary> 
		/// discussion2 control. 
		/// </summary> 
		/// <remarks> 
		/// Auto-generated field. 
		/// To modify move field declaration from designer file to code-behind file. 
		/// </remarks> 
		protected global::System.Web.UI.WebControls.Button discussion2;
	}
}
